# config.yaml
TWITCH_OAUTH_TOKEN: rgl1ncmyll1u4hdvkv3or6owaoy901
TWITCH_CHANNEL: profesorcerebron
IGNORED_USERS:
  - profesorcerebron
  - streamelements
  - wizebot
  - serybot
IGNORED_MESSAGES_STARTS_WITH:
  - http://
  - https://
COMMAND: '!voz'
HELP_MESSAGE: '/me Para cambiar tu voz utiliza !voz [voz], voces disponibles: Carlos, Jorge, Diego, Javier, PaulinaMl, Angelica, Isabela, Francisca, Soledad. Por ejemplo: !voz Carlos'